/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.xwpf.app;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;

/**
 *
 * @author x
 */
public class MainPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MainPanel
	 */
	public MainPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Process");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessDoc(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProcessDoc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessDoc
		// TODO add your handling code here:
		JButton b = jButton1;

		File fileToBeSent = null;
		FileInputStream in = null;
		try {

			if (evt.getSource() == b) {
				JFileChooser fc = new JFileChooser();
				fc.setBackground(new java.awt.Color(102, 255, 153));
				fc.setDialogTitle("Choose Word Document");
				fc.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
				fc.setToolTipText("");
				fc.setAutoscrolls(true);
				fc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 153), new java.awt.Color(0, 255, 153), new java.awt.Color(0, 255, 150), new java.awt.Color(0, 255, 150)));
				fc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
				fc.getAccessibleContext().setAccessibleParent(jButton1);
				int x = fc.showOpenDialog(null);
				if (x == JFileChooser.APPROVE_OPTION) {
					fileToBeSent = fc.getSelectedFile();
					in = new FileInputStream(fileToBeSent);
					Process pc = new Process(in);

				} else {
					fileToBeSent = null;
				}
			}
		} catch (FileNotFoundException ex) {
			Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IOException ex) {
			Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
		} finally {
			try {
				in.close();
			} catch (Exception exp) {
			}
    }//GEN-LAST:event_ProcessDoc
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
